/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreateFileRequest {
  'name' : string,
  'size' : bigint,
  'mimeType' : string,
  'folderId' : [] | [FolderId],
  'objectStorageKey' : string,
}
export interface CreateFolderRequest {
  'name' : string,
  'parentFolderId' : [] | [FolderId],
}
export type FileId = bigint;
export interface FileMeta {
  'id' : FileId,
  'isDeleted' : boolean,
  'owner' : Principal,
  'name' : string,
  'size' : bigint,
  'mimeType' : string,
  'folderId' : [] | [FolderId],
  'objectStorageKey' : string,
  'uploadedAt' : Time,
}
export interface Folder {
  'id' : FolderId,
  'owner' : Principal,
  'name' : string,
  'createdAt' : Time,
  'parentFolderId' : [] | [FolderId],
}
export type FolderId = bigint;
export interface StorageStats { 'totalFiles' : bigint, 'totalBytes' : bigint }
export type Time = bigint;
export interface UpdateFileRequest {
  'id' : FileId,
  'name' : string,
  'folderId' : [] | [FolderId],
}
export interface UpdateFolderRequest {
  'id' : FolderId,
  'name' : string,
  'parentFolderId' : [] | [FolderId],
}
export interface UserProfile { 'displayName' : string, 'owner' : Principal }
export interface _SERVICE {
  'createFile' : ActorMethod<[CreateFileRequest], FileMeta>,
  'createFolder' : ActorMethod<[CreateFolderRequest], Folder>,
  'deleteFile' : ActorMethod<[FileId], boolean>,
  'deleteFolder' : ActorMethod<[FolderId], boolean>,
  'getFile' : ActorMethod<[FileId], [] | [FileMeta]>,
  'getFolder' : ActorMethod<[FolderId], [] | [Folder]>,
  'getStorageStats' : ActorMethod<[], StorageStats>,
  'getUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'listFilesByCategory' : ActorMethod<[string], Array<FileMeta>>,
  'listFilesByFolder' : ActorMethod<[[] | [FolderId]], Array<FileMeta>>,
  'listFolders' : ActorMethod<[[] | [FolderId]], Array<Folder>>,
  'searchFiles' : ActorMethod<[string], Array<FileMeta>>,
  'setUserProfile' : ActorMethod<[string], undefined>,
  'updateFile' : ActorMethod<[UpdateFileRequest], boolean>,
  'updateFolder' : ActorMethod<[UpdateFolderRequest], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];