/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FolderId = IDL.Nat;
export const CreateFileRequest = IDL.Record({
  'name' : IDL.Text,
  'size' : IDL.Nat,
  'mimeType' : IDL.Text,
  'folderId' : IDL.Opt(FolderId),
  'objectStorageKey' : IDL.Text,
});
export const FileId = IDL.Nat;
export const Time = IDL.Int;
export const FileMeta = IDL.Record({
  'id' : FileId,
  'isDeleted' : IDL.Bool,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'size' : IDL.Nat,
  'mimeType' : IDL.Text,
  'folderId' : IDL.Opt(FolderId),
  'objectStorageKey' : IDL.Text,
  'uploadedAt' : Time,
});
export const CreateFolderRequest = IDL.Record({
  'name' : IDL.Text,
  'parentFolderId' : IDL.Opt(FolderId),
});
export const Folder = IDL.Record({
  'id' : FolderId,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
  'parentFolderId' : IDL.Opt(FolderId),
});
export const StorageStats = IDL.Record({
  'totalFiles' : IDL.Nat,
  'totalBytes' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'owner' : IDL.Principal,
});
export const UpdateFileRequest = IDL.Record({
  'id' : FileId,
  'name' : IDL.Text,
  'folderId' : IDL.Opt(FolderId),
});
export const UpdateFolderRequest = IDL.Record({
  'id' : FolderId,
  'name' : IDL.Text,
  'parentFolderId' : IDL.Opt(FolderId),
});

export const idlService = IDL.Service({
  'createFile' : IDL.Func([CreateFileRequest], [FileMeta], []),
  'createFolder' : IDL.Func([CreateFolderRequest], [Folder], []),
  'deleteFile' : IDL.Func([FileId], [IDL.Bool], []),
  'deleteFolder' : IDL.Func([FolderId], [IDL.Bool], []),
  'getFile' : IDL.Func([FileId], [IDL.Opt(FileMeta)], ['query']),
  'getFolder' : IDL.Func([FolderId], [IDL.Opt(Folder)], ['query']),
  'getStorageStats' : IDL.Func([], [StorageStats], ['query']),
  'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'listFilesByCategory' : IDL.Func([IDL.Text], [IDL.Vec(FileMeta)], ['query']),
  'listFilesByFolder' : IDL.Func(
      [IDL.Opt(FolderId)],
      [IDL.Vec(FileMeta)],
      ['query'],
    ),
  'listFolders' : IDL.Func([IDL.Opt(FolderId)], [IDL.Vec(Folder)], ['query']),
  'searchFiles' : IDL.Func([IDL.Text], [IDL.Vec(FileMeta)], ['query']),
  'setUserProfile' : IDL.Func([IDL.Text], [], []),
  'updateFile' : IDL.Func([UpdateFileRequest], [IDL.Bool], []),
  'updateFolder' : IDL.Func([UpdateFolderRequest], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FolderId = IDL.Nat;
  const CreateFileRequest = IDL.Record({
    'name' : IDL.Text,
    'size' : IDL.Nat,
    'mimeType' : IDL.Text,
    'folderId' : IDL.Opt(FolderId),
    'objectStorageKey' : IDL.Text,
  });
  const FileId = IDL.Nat;
  const Time = IDL.Int;
  const FileMeta = IDL.Record({
    'id' : FileId,
    'isDeleted' : IDL.Bool,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'size' : IDL.Nat,
    'mimeType' : IDL.Text,
    'folderId' : IDL.Opt(FolderId),
    'objectStorageKey' : IDL.Text,
    'uploadedAt' : Time,
  });
  const CreateFolderRequest = IDL.Record({
    'name' : IDL.Text,
    'parentFolderId' : IDL.Opt(FolderId),
  });
  const Folder = IDL.Record({
    'id' : FolderId,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
    'parentFolderId' : IDL.Opt(FolderId),
  });
  const StorageStats = IDL.Record({
    'totalFiles' : IDL.Nat,
    'totalBytes' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'owner' : IDL.Principal,
  });
  const UpdateFileRequest = IDL.Record({
    'id' : FileId,
    'name' : IDL.Text,
    'folderId' : IDL.Opt(FolderId),
  });
  const UpdateFolderRequest = IDL.Record({
    'id' : FolderId,
    'name' : IDL.Text,
    'parentFolderId' : IDL.Opt(FolderId),
  });
  
  return IDL.Service({
    'createFile' : IDL.Func([CreateFileRequest], [FileMeta], []),
    'createFolder' : IDL.Func([CreateFolderRequest], [Folder], []),
    'deleteFile' : IDL.Func([FileId], [IDL.Bool], []),
    'deleteFolder' : IDL.Func([FolderId], [IDL.Bool], []),
    'getFile' : IDL.Func([FileId], [IDL.Opt(FileMeta)], ['query']),
    'getFolder' : IDL.Func([FolderId], [IDL.Opt(Folder)], ['query']),
    'getStorageStats' : IDL.Func([], [StorageStats], ['query']),
    'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'listFilesByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(FileMeta)],
        ['query'],
      ),
    'listFilesByFolder' : IDL.Func(
        [IDL.Opt(FolderId)],
        [IDL.Vec(FileMeta)],
        ['query'],
      ),
    'listFolders' : IDL.Func([IDL.Opt(FolderId)], [IDL.Vec(Folder)], ['query']),
    'searchFiles' : IDL.Func([IDL.Text], [IDL.Vec(FileMeta)], ['query']),
    'setUserProfile' : IDL.Func([IDL.Text], [], []),
    'updateFile' : IDL.Func([UpdateFileRequest], [IDL.Bool], []),
    'updateFolder' : IDL.Func([UpdateFolderRequest], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };