/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UpdateFileRequest {
    id: FileId;
    name: string;
    folderId?: FolderId;
}
export interface StorageStats {
    totalFiles: bigint;
    totalBytes: bigint;
}
export type Time = bigint;
export interface UpdateFolderRequest {
    id: FolderId;
    name: string;
    parentFolderId?: FolderId;
}
export interface Folder {
    id: FolderId;
    owner: Principal;
    name: string;
    createdAt: Time;
    parentFolderId?: FolderId;
}
export interface FileMeta {
    id: FileId;
    isDeleted: boolean;
    owner: Principal;
    name: string;
    size: bigint;
    mimeType: string;
    folderId?: FolderId;
    objectStorageKey: string;
    uploadedAt: Time;
}
export type FileId = bigint;
export interface CreateFolderRequest {
    name: string;
    parentFolderId?: FolderId;
}
export interface CreateFileRequest {
    name: string;
    size: bigint;
    mimeType: string;
    folderId?: FolderId;
    objectStorageKey: string;
}
export type FolderId = bigint;
export interface UserProfile {
    displayName: string;
    owner: Principal;
}
export interface backendInterface {
    createFile(req: CreateFileRequest): Promise<FileMeta>;
    createFolder(req: CreateFolderRequest): Promise<Folder>;
    deleteFile(id: FileId): Promise<boolean>;
    deleteFolder(id: FolderId): Promise<boolean>;
    getFile(id: FileId): Promise<FileMeta | null>;
    getFolder(id: FolderId): Promise<Folder | null>;
    getStorageStats(): Promise<StorageStats>;
    getUserProfile(): Promise<UserProfile | null>;
    listFilesByCategory(mimeTypePrefix: string): Promise<Array<FileMeta>>;
    listFilesByFolder(folderId: FolderId | null): Promise<Array<FileMeta>>;
    listFolders(parentFolderId: FolderId | null): Promise<Array<Folder>>;
    searchFiles(nameSubstring: string): Promise<Array<FileMeta>>;
    setUserProfile(displayName: string): Promise<void>;
    updateFile(req: UpdateFileRequest): Promise<boolean>;
    updateFolder(req: UpdateFolderRequest): Promise<boolean>;
}
import type { CreateFileRequest as _CreateFileRequest, CreateFolderRequest as _CreateFolderRequest, FileId as _FileId, FileMeta as _FileMeta, Folder as _Folder, FolderId as _FolderId, Time as _Time, UpdateFileRequest as _UpdateFileRequest, UpdateFolderRequest as _UpdateFolderRequest, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createFile(arg0: CreateFileRequest): Promise<FileMeta> {
        if (this.processError) {
            try {
                const result = await this.actor.createFile(to_candid_CreateFileRequest_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_FileMeta_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFile(to_candid_CreateFileRequest_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_FileMeta_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async createFolder(arg0: CreateFolderRequest): Promise<Folder> {
        if (this.processError) {
            try {
                const result = await this.actor.createFolder(to_candid_CreateFolderRequest_n6(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Folder_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFolder(to_candid_CreateFolderRequest_n6(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Folder_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteFile(arg0: FileId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFile(arg0);
            return result;
        }
    }
    async deleteFolder(arg0: FolderId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFolder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFolder(arg0);
            return result;
        }
    }
    async getFile(arg0: FileId): Promise<FileMeta | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFolder(arg0: FolderId): Promise<Folder | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFolder(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFolder(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStorageStats(): Promise<StorageStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getStorageStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStorageStats();
            return result;
        }
    }
    async getUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async listFilesByCategory(arg0: string): Promise<Array<FileMeta>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFilesByCategory(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFilesByCategory(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async listFilesByFolder(arg0: FolderId | null): Promise<Array<FileMeta>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFilesByFolder(to_candid_opt_n14(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFilesByFolder(to_candid_opt_n14(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async listFolders(arg0: FolderId | null): Promise<Array<Folder>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFolders(to_candid_opt_n14(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFolders(to_candid_opt_n14(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchFiles(arg0: string): Promise<Array<FileMeta>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchFiles(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchFiles(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async setUserProfile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserProfile(arg0);
            return result;
        }
    }
    async updateFile(arg0: UpdateFileRequest): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFile(to_candid_UpdateFileRequest_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFile(to_candid_UpdateFileRequest_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateFolder(arg0: UpdateFolderRequest): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFolder(to_candid_UpdateFolderRequest_n18(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFolder(to_candid_UpdateFolderRequest_n18(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_FileMeta_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FileMeta): FileMeta {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Folder_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Folder): Folder {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FileMeta]): FileMeta | null {
    return value.length === 0 ? null : from_candid_FileMeta_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Folder]): Folder | null {
    return value.length === 0 ? null : from_candid_Folder_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FolderId]): FolderId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _FileId;
    isDeleted: boolean;
    owner: Principal;
    name: string;
    size: bigint;
    mimeType: string;
    folderId: [] | [_FolderId];
    objectStorageKey: string;
    uploadedAt: _Time;
}): {
    id: FileId;
    isDeleted: boolean;
    owner: Principal;
    name: string;
    size: bigint;
    mimeType: string;
    folderId?: FolderId;
    objectStorageKey: string;
    uploadedAt: Time;
} {
    return {
        id: value.id,
        isDeleted: value.isDeleted,
        owner: value.owner,
        name: value.name,
        size: value.size,
        mimeType: value.mimeType,
        folderId: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.folderId)),
        objectStorageKey: value.objectStorageKey,
        uploadedAt: value.uploadedAt
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _FolderId;
    owner: Principal;
    name: string;
    createdAt: _Time;
    parentFolderId: [] | [_FolderId];
}): {
    id: FolderId;
    owner: Principal;
    name: string;
    createdAt: Time;
    parentFolderId?: FolderId;
} {
    return {
        id: value.id,
        owner: value.owner,
        name: value.name,
        createdAt: value.createdAt,
        parentFolderId: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.parentFolderId))
    };
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FileMeta>): Array<FileMeta> {
    return value.map((x)=>from_candid_FileMeta_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Folder>): Array<Folder> {
    return value.map((x)=>from_candid_Folder_n8(_uploadFile, _downloadFile, x));
}
function to_candid_CreateFileRequest_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateFileRequest): _CreateFileRequest {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_CreateFolderRequest_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateFolderRequest): _CreateFolderRequest {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateFileRequest_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateFileRequest): _UpdateFileRequest {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateFolderRequest_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateFolderRequest): _UpdateFolderRequest {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FolderId | null): [] | [_FolderId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: FileId;
    name: string;
    folderId?: FolderId;
}): {
    id: _FileId;
    name: string;
    folderId: [] | [_FolderId];
} {
    return {
        id: value.id,
        name: value.name,
        folderId: value.folderId ? candid_some(value.folderId) : candid_none()
    };
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: FolderId;
    name: string;
    parentFolderId?: FolderId;
}): {
    id: _FolderId;
    name: string;
    parentFolderId: [] | [_FolderId];
} {
    return {
        id: value.id,
        name: value.name,
        parentFolderId: value.parentFolderId ? candid_some(value.parentFolderId) : candid_none()
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    size: bigint;
    mimeType: string;
    folderId?: FolderId;
    objectStorageKey: string;
}): {
    name: string;
    size: bigint;
    mimeType: string;
    folderId: [] | [_FolderId];
    objectStorageKey: string;
} {
    return {
        name: value.name,
        size: value.size,
        mimeType: value.mimeType,
        folderId: value.folderId ? candid_some(value.folderId) : candid_none(),
        objectStorageKey: value.objectStorageKey
    };
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    parentFolderId?: FolderId;
}): {
    name: string;
    parentFolderId: [] | [_FolderId];
} {
    return {
        name: value.name,
        parentFolderId: value.parentFolderId ? candid_some(value.parentFolderId) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
